# More details in https://bookdown.org/yihui/blogdown/templates.html
# Issues at https://github.com/yihui/hugo-xmin/issues?utf8=%E2%9C%93&q=+


title = "A minimal Hugo website"
googleAnalytics = ""
disqusShortname = ""

theme = "hugo-xmin"

# Option 1) Project Github Page
# baseURL = "https://lulliter.github.io/blog/" # https://[USERNAME].github.io/[REPO_NAME] in this case (Github Page)

# Option 2) Redirecting Project Github Page to personal GOOGLE DOMAIN (@ gmail)
# Following https://medium.com/@hossainkhan/using-custom-domain-for-github-pages-86b303d3918a
baseURL = "https://luisamimmi.com/"
relativeURLs = true
publishDir = "docs" # By default would be /public We need it to be the /docs (Github docs branch)
languageCode = "en-us"
draft = false # if set to true, changes will not be published
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
enableEmoji = true

footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    #note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Portfolio"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
[[menu.main]]
    name = "CV"
    url = "/cv/" # "/cv_files/Luisa-M-Mimmi_CV.pdf"
    weight = 4



#[[menu.main]]
#    name = "Tags"
#    url = "/tags/"
#    weight = 4
#[[menu.main]]
#    name = "Subscribe"
#    url = "/index.xml"

[params]
    description = "Personal website & portfolio."
    footer = "&copy; Luisa M. Mimmi 2018 -- 2019 | _Built with Blogdown & Hugo ([XMin](https://themes.gohugo.io/hugo-xmin/)), deployed on Github Pages_"
