---
title: (in progress) Policy - random thoughts
author: Luisa M. Mimmi
date: '2020-01-16'
slug: policy-thoughts
categories:
  - Blog-post
tags:
  - Policy
  - G20
---
# Totalitarismo

"Nel 1951 la teorica della politica Hannah Arendt pubblicò  _Le origini del totalitarismo_: **il piu importante indicatore del totalitarismo e' la solitudine e l'alienazione di massa**. (...) ALtri fattori citati dalla Arendt sono una diffusa perdita di fiducia nelle istituzioni e nelle gerarchie e una inclinazione alla trasgressione e alla distruzione (USA 2020). (...) La Arendt diceva anche che **una società pre-totalitaria e' quella in cui le persone hanno cessato di occuparsi della verità e credono invece a cio che le fa sentire bene**. (vedi censura del discorso pubblico e soffocamento delle voci che sfidano l'ideologia culturale dominante).  

  
# Resilienza

[Stefano Zamagni "Meet the Meeting"](https://www.meetingrimini.org/en/meet-the-meeting-dal-palacongressi-di-rimini-il-racconto-della-special-edition-del-meeting-2020/) 23 Maggio 2020

Occorre non più *riformare* ma ripensare con **resilienza trasformativa** applicata almeno a 3 blocchi:

1. Scuola/Ricerca: basta coll'impianto taylorista entrato anche nella scuola/università (luogo di istruzione, ma non educazione)
2. Dal welfare state al **welfare di comunità**. Sussidiarietà (principio sancito dalla Costituzione art. 118 ma mai applicato)
3. Sistema fiscale: i **progetti produttivi devono pagare meno tasse** dei progetti improduttivi
4. Deburocratizzazione: 161000 leggi vigenti in Italia (in Germania 7000). Xche? cultura del sospetto - x colpire uno, impedisco a 100 altri di fare quel che vorrebbero
5. Aumentare il tasso di imprenditorialita' 

# Immigration

+ _"Aiutiamoli a casa loro" _- many think that ODA would be the step to keep people in Africa, whereas observation of incoming economic migrants shows that those travelling are not the most destitute, but the slightly better off. 
Hence - in the short term - aid is likely to make more people better off so much so to become candidates for leaving _(Source: ISPI podcast)_



# Climate change 
+ [Mckinsey Report](https://www.mckinsey.com/business-functions/sustainability/our-insights/climate-risk-and-response-physical-hazards-and-socioeconomic-impacts?cid=other-eml-alt-mgi-mck&hlkid=14c6e658a93041d5aa2124274d4cd08c&hctky=2352551&hdpid=5c80f35f-d47f-41c6-acdd-8e249d1f0b52)
