---
title: G20 - journal
author: Luisa M. Mimmi
date: '2020-02-07'
categories:
  - Blog-post
  - journal
tags:
  - G20
  - Policy
slug: g20-journal
draft: true
---


# Week Feb3-Feb7, 2020

+ IMF-MEF workshop on "Brainstorming topics for Italy's G20 presidency"

[Agenda-Lula](/post/G20ref/IMF_Workshop_PeopleNotes_3-4feb2020.pdf)

[Minutes](/post/G20ref/IMFworkshop_ExSum_3-4Feb2020.pdf)

+ Presentazione Prof. [A. Roventini](https://www.santannapisa.it/it/andrea-roventini) "Il rischio e le opportunita del cambiamento climatico" (CDP think tank, 5 Feb 2020)
	
SPUNTI: Collaborates with Mariana Mazzucato	/ catastrofista, ma ammette incertezza "knightiana" ... / darsi obiettivi intermedi (e.g. 100 carbon-neutral cities by 2030) / il mix di finanziamento cambia da caso a caso (es eolico a terra vs eolico off shore) 

+ Min Difesa - MEF (F. Diamanti, ) brainstorming on GEOSPATIAL OPPORTUNITIES 
With 
	- *Gen. B. Fortunato Di Marzi* Vice Direttore del III Reparto Politica Industriale e Rel Internazionali, 
	- Ufficio di programma per i sistemi e le applicazioni e coop. spaziali *Col. Raffaele IOVINO*

SPUNTI: direzione e coordinamento di programmi internazionali e nazionali di sviluppo, produzione e approvvigionamento nel settore Spaziale e predisposizione dei relativi accordi tecnici.
L'Italia con CosmoSkyMEd ha una capacita di "spennellare tutta la terra" (radar & ottico) con risoluzione altissima: 
		- 50 cm (anche uso civile)
		- <50cm (solo uso militare) 
Da contattare GEOS (progetto MapItaly, amazzonia ecc.)

** Il punto e' che una volta che hai questi assets puoi usarli come vuoi (militare o civile... e' solo l'ultimo miglio che cambia)

<!-- [Code on Github](https://github.com/Lulliter/DECdatascience) -->

